// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a ModelGenerator.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
namespace Disbot.Models
{
	//You can get Utilities package via nuget : Install-Package Deszolate.Utilities.Lite
	//[Utilities.Attributes.SQL.Table("ExceptionLog")]
	public partial class ExceptionLog
	{
		public string Function { get; set; }
		public string Content { get; set; }
		public DateTime? Date { get; set; }
	}
}

