// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a ModelGenerator.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using Utilities.Attributes.SQL;

namespace Disbot.Models
{
    //You can get Utilities package via nuget : Install-Package Deszolate.Utilities.Lite
    //[Utilities.Attributes.SQL.Table("Member")]
    public partial class Member
    {
        [PrimaryKey(false)]
        public long? ID { get; set; }
        public string Username { get; set; }
        public string DisplayName { get; set; }
        public string AvatarUrl { get; set; }
        public uint Level { get; set; }
        public float Exp { get; set; }
        public float NextExp { get; set; }
    }
}

