// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a ModelGenerator.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
namespace Disbot.Models
{
	//You can get Utilities package via nuget : Install-Package Deszolate.Utilities.Lite
	//[Utilities.Attributes.SQL.Table("MessageHistory")]
	public partial class MessageHistory
	{
		public long? MemberID { get; set; }
		public string Message { get; set; }
		public DateTime? CreateDate { get; set; }
	}
}

